import GetUrlParams from "@/helpers/utilities/getUrlParams";
import DefaultConfig from "./default";

const { utm_source = null } = GetUrlParams();
let Config;

switch (utm_source) {
  default:
    Config = DefaultConfig;
}

export const {
  FB_APP_ID,
  FB_PAGE_ID,
  CMS,
  SITE_ID,
  SITE_NAME,
  SITE_URL,
  BASE_S3_URL,
  PORTAL_CDN_URL,
  INSTAGRAM_API_URL,
  INSTAGRAM_URL,
  AMAZON_URL,
  AMAZON_ADS_URL,
  JW_PLAYER_URL,
  JW_PLATFORM_CONTENT_URL,
  FACEBOOK_URL,
  FACEBOOKCONNECT_URL,
  TIKTOK_URL,
  YOUTUBE_URL,
  IMAGEKIT_URL,
  KLAVIYO_URL,
  TWITTER_URL,
  GOOGLE_ANALYTICS_URL,
  GOOGLE_STORAGE_URL,
  GOOGLE_FONTSTATIC_URL,
  GOOGLE_FONTSAPI_URL,
  GOOGLE_TAG_SERVICES_URL,
  GOOGLE_MAPS_URL,
  GOOGLE_SECOND_MAPS_URL,
  WHISK_URL,
  SHOPIFYSDK_URL,
  ONETAG_URL,
  PRIMIS_URL,
  OMNITAG_URL,
  SEKINDO_URL,
  UNSPLASH_URL,
  TWITTER_PLATFORM_URL,
  TRANSITION_DURATION,
  AVAILABLE_AD_SLOTS,
  AD_SPACING,
//   AD_AUCTION_TIMEOUT,
  AD_INITIAL_POSITION,
  JW_PLAYER_SCRIPT_ID,
  UNRULY_SITE_ID,
  KLAVIYO_PUBLIC_API_KEY,
  GOOGLE_MAPS_API_KEY,
  CRYPTO_SECRET,
  GPT_AD_UNITS,
  VISIBILITY_OFFSET,
  PREBID_TIMEOUT,
  PUB_ID,
  PLAYWIRE_AD_UNIT_CONTENT,
  PLAYWIRE_AD_UNIT_CONTENT_2,
  SNACKBAR_DESKTOP_AD_UNIT_CONTENT,
  SNACKBAR_MOBILE_AD_UNIT_CONTENT,
  SNACKBAR_AD_UNIT_CONTENT,
} = Config;
